### ISSUE TITLE
No support for a missing background page / content script

### ISSUE THREAD

**Issue by Luca-Pistor** [Aurore54F/DoubleX#2]
Currently, DoubleX will throw an error if its command-line invocation is missing either a -cs or -bp argument. We can work around this by creating a blank text file to process as an empty argument, but support for extensions without content scripts (resp. background pages) would be useful.

**Comment by Aurore54F** [comment]
Fixed, thanks. Parameters -cs and -bp are now optional. If nothing is specified an empty JS file from the folder _empty_ will be analyzed.

Note: to extract content scripts and background scripts from an extension, the _src/unpack_extension.py_ script can be called, though.
