### ISSUE TITLE
Timing information

### ISSUE THREAD

**Issue by Luca-Pistor** [Aurore54F/DoubleX#3]
Currently, running a DoubleX program will not print information to stdout until it finishes processing an extension, or an error occurs. This may make it difficult to determine how much time is left in various processing phases, which would be useful for processing large extensions.

**Comment by Aurore54F** [comment]
Thanks. Added info and benchmark for the following steps (note elements 1-4 refer to the content script (cs) and 5-8 to the background page (bp); WA later refers to a Web Application):

CURRENT STATE Successfully got Esprima AST in XXXs
CURRENT STATE Successfully produced the AST in XXXs
CURRENT STATE Successfully produced the CFG in XXXs
CURRENT STATE Successfully produced the PDG in XXXs
CURRENT STATE Successfully got Esprima AST in XXXs
CURRENT STATE Successfully produced the AST in XXXs
CURRENT STATE Successfully produced the CFG in XXXs
CURRENT STATE Successfully produced the PDG in XXXs
CURRENT STATE Successfully collected all messages exchanged in XXXs
CURRENT STATE Successfully linked the messages sent and received in XXXs
CURRENT STATE Successfully collected the dangers and elements from the WA in the cs in XXXs
CURRENT STATE Successfully collected the dangers and elements from the WA in the bp in XXXs
CURRENT STATE Successfully analyzed and collected the vulnerabilities in the cs in XXXs
CURRENT STATE Successfully analyzed and collected the vulnerabilities in the bp in XXXs
